In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
grid_param={'n_estimators':[10,50,100],'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'max_features':['auto','sqrt','log2']}

grid=GridSearchCV(RandomForestRegressor(),grid_param,refit=True,verbose=3,n_jobs=-1)
grid.fit(indepen,depen)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
53 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.80713041 0.83070321 0.83296181
 0.8120234  0.83142779 0.83313836        nan        nan        nan
 0.8166378  0.8299663  0.83285598 0.81716515 0.83152714 0.83149575
        nan        nan        nan 0.81907174 0.83098762 0.83460266
 0.81423391 0.83224744 0.83219581        nan        nan        nan
 0.81756118 0.82947277 0.83473747 0.81811784 0.83299388 0.83384393]
  warnings.warn(
C:\Anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [7]:
result=grid.cv_results_
grid_prediction=grid.predict(indepen)

from sklearn.metrics import r2_score
r=r2_score(depen,grid_prediction)
print('The R_score value for best parameters :',format(grid.best_params_),r)

The R_score value for best parameters : {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100} 0.9764949916474914

In [8]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001725,0.000267,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
1,0.001505,0.000157,0.000000,0.000000,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2,0.001554,0.000250,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
3,0.038473,0.000672,0.005370,0.000369,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.840691,0.748566,0.830753,0.804031,0.811611,0.807130,0.032074,24
4,0.166150,0.003932,0.012030,0.000417,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.857168,0.778882,0.850338,0.828141,0.838987,0.830703,0.027736,14
5,0.317433,0.002770,0.019750,0.000829,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.859885,0.779068,0.857487,0.828997,0.839372,0.832962,0.029284,6
6,0.035542,0.001578,0.004904,0.000409,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.821631,0.759788,0.837859,0.807379,0.833459,0.812023,0.028176,23
7,0.161791,0.003954,0.012216,0.000964,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.854077,0.784397,0.854768,0.827047,0.836850,0.831428,0.025761,12
8,0.349709,0.022979,0.023748,0.002353,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.857362,0.778379,0.859987,0.829736,0.840228,0.833138,0.029557,4
9,0.001394,0.000305,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
10,0.001356,0.000319,0.000000,0.000000,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
11,0.002071,0.001055,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
12,0.041708,0.003387,0.005806,0.000548,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.840353,0.754723,0.848452,0.818997,0.820664,0.816638,0.032954,21
13,0.176407,0.012857,0.012024,0.001040,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.850254,0.773149,0.861921,0.830217,0.834291,0.829966,0.030593,15
14,0.318491,0.013225,0.019368,0.000897,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.859942,0.775286,0.864347,0.827360,0.837344,0.832856,0.031906,7
15,0.036263,0.000827,0.004930,0.000491,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.832862,0.765830,0.848511,0.810897,0.827725,0.817165,0.028338,20
16,0.160351,0.003274,0.011587,0.000818,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.852886,0.777506,0.855424,0.830205,0.841614,0.831527,0.028457,10
17,0.316720,0.008037,0.020767,0.001142,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.856530,0.777943,0.857062,0.824355,0.841589,0.831496,0.029329,11
18,0.001762,0.001160,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
19,0.001133,0.000050,0.000000,0.000000,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
20,0.001167,0.000054,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
21,0.099549,0.002493,0.004731,0.000259,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.839375,0.766922,0.837730,0.814433,0.836899,0.819072,0.027638,17
22,0.601957,0.128405,0.014331,0.006131,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.854445,0.773959,0.851437,0.826753,0.848345,0.830988,0.030133,13
23,1.015161,0.119388,0.018670,0.000540,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856342,0.780969,0.863489,0.826728,0.845485,0.834603,0.029543,2
24,0.150646,0.064767,0.004697,0.000232,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.837611,0.769819,0.827151,0.811285,0.825303,0.814234,0.023737,22
25,0.493478,0.010332,0.011484,0.000939,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.858373,0.781024,0.851904,0.824001,0.845935,0.832247,0.028100,8
26,0.951878,0.007739,0.018743,0.000808,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.859466,0.778976,0.855005,0.826500,0.841031,0.832196,0.029006,9
27,0.001259,0.000281,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
28,0.001314,0.000388,0.000000,0.000000,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
29,0.001255,0.000281,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
30,0.038439,0.001718,0.004708,0.000263,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.847285,0.766481,0.842789,0.806387,0.824864,0.817561,0.029351,19
31,0.169411,0.006904,0.011100,0.000342,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.850648,0.773763,0.855966,0.828344,0.838643,0.829473,0.029459,16
32,0.334274,0.007254,0.019148,0.000710,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859148,0.781254,0.860597,0.831131,0.841557,0.834737,0.028930,1
33,0.037717,0.001531,0.004570,0.000054,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.840538,0.772652,0.845682,0.808029,0.823688,0.818118,0.026315,18
34,0.172044,0.003255,0.011623,0.000536,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.855491,0.782294,0.857830,0.829907,0.839448,0.832994,0.027366,5
35,0.324894,0.002921,0.018730,0.000435,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.857731,0.781602,0.862766,0.826760,0.840361,0.833844,0.029083,3

In [9]:
age_input=int(input("AGE :"))
bmi_input=float(input('BMI :'))
chlidren_input=int(input("children : "))
sex_input=int(input("sex 0 or 1:"))
smoker_input=int(input("smoker 0 or 1:"))

AGE : 30
BMI : 27.666
children :  0
sex 0 or 1: 0
smoker 0 or 1: 0

In [10]:
future_prediction=grid.predict([[age_input,bmi_input,chlidren_input,sex_input,smoker_input]])
print("future prediction=",format(future_prediction))

future prediction= [3744.8214555]

C:\Anaconda\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(