In [1]:
import numpy as ny
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indepen=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
depen=dataset[['charges']]

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(indepen,depen,test_size=1/3,random_state=0)

In [8]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor
grid_param={'n_estimators':[10,50,100],'criterion':['squared_error','friedman_mse','absolute_error','poisson'],
            'max_features':['auto','sqrt','log2']}

grid=GridSearchCV(RandomForestRegressor(),grid_param,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning:
60 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
44 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
16 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anaconda\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 1382, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Anaconda\Lib\site-packages\sklearn\base.py", line 436, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Anaconda\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anaconda\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan 0.77974485 0.79926125 0.80367144
 0.77163319 0.79618289 0.79872468        nan        nan        nan
 0.77653927 0.79648609 0.80161344 0.77397259 0.79815032 0.79870823
        nan        nan        nan 0.78353396 0.79656788 0.80231474
 0.7802529  0.79707317 0.80089983        nan        nan        nan
 0.7841823  0.79825262 0.79974702 0.78418138 0.80148002 0.80121819]
  warnings.warn(
C:\Anaconda\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 50, 100]},
             verbose=3)

In [9]:
result=grid.cv_results_
grid_prediction=grid.predict(x_test)

from sklearn.metrics import r2_score
r=r2_score(y_test,grid_prediction)
print("The R_score value for the best parameter :",format(grid.best_params_),r)

The R_score value for the best parameter : {'criterion': 'squared_error', 'max_features': 'sqrt', 'n_estimators': 100} 0.8703767699441887

In [10]:
table=pd.DataFrame.from_dict(result)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001756,0.000203,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
1,0.001436,0.000095,0.000000,0.000000,squared_error,auto,50,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
2,0.001426,0.000063,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
3,0.091028,0.008282,0.006776,0.002541,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.779652,0.742862,0.825044,0.806229,0.744937,0.779745,0.032636,21
4,0.298681,0.049771,0.018495,0.007564,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.806808,0.767530,0.841176,0.825669,0.755123,0.799261,0.033064,8
5,0.614336,0.045227,0.041432,0.013187,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.805825,0.775279,0.839596,0.835598,0.762059,0.803671,0.031152,1
6,0.155839,0.102421,0.020601,0.010810,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.777084,0.719898,0.808025,0.799783,0.753375,0.771633,0.032113,24
7,0.264924,0.026194,0.018457,0.010303,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.796726,0.778186,0.835735,0.817845,0.752423,0.796183,0.029233,16
8,0.591000,0.023194,0.028816,0.006497,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.800437,0.764494,0.836072,0.832683,0.759937,0.798725,0.032333,9
9,0.001322,0.000040,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
10,0.001386,0.000046,0.000000,0.000000,friedman_mse,auto,50,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
11,0.001410,0.000218,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
12,0.110907,0.044453,0.007614,0.002260,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.764565,0.761473,0.816355,0.787930,0.752374,0.776539,0.023106,22
13,0.291735,0.024982,0.023693,0.013189,friedman_mse,sqrt,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.792552,0.772262,0.830954,0.828081,0.758580,0.796486,0.029071,15
14,0.648459,0.041283,0.033209,0.012885,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.800352,0.771630,0.837214,0.833966,0.764905,0.801613,0.030207,3
15,0.097691,0.013103,0.021603,0.014099,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.805819,0.729385,0.805652,0.798312,0.730695,0.773973,0.035976,23
16,0.319242,0.056818,0.012367,0.000496,friedman_mse,log2,50,"{'criterion': 'friedman_mse', 'max_features': ...",0.804620,0.762501,0.833012,0.834723,0.755895,0.798150,0.033619,12
17,0.613435,0.016415,0.051203,0.015047,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.805729,0.761797,0.838471,0.828437,0.759106,0.798708,0.033000,10
18,0.001365,0.000042,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
19,0.001422,0.000172,0.000000,0.000000,absolute_error,auto,50,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
20,0.001353,0.000035,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
21,0.129961,0.009228,0.005609,0.000212,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.792109,0.755890,0.824336,0.790154,0.755181,0.783534,0.025886,19
22,0.766174,0.032020,0.020242,0.013388,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.799677,0.775563,0.833491,0.820215,0.753893,0.796568,0.028964,14
23,1.606737,0.090889,0.052413,0.016449,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.802290,0.774047,0.839884,0.832664,0.762690,0.802315,0.030665,2
24,0.189285,0.033816,0.005688,0.000163,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.798932,0.741385,0.836314,0.785394,0.739240,0.780253,0.036636,20
25,0.818448,0.057345,0.020149,0.013513,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.798204,0.765166,0.830569,0.833695,0.757733,0.797073,0.031718,13
26,1.640050,0.177299,0.040681,0.013844,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.802782,0.774238,0.835417,0.825085,0.766976,0.800900,0.026987,6
27,0.001585,0.000425,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
28,0.001432,0.000090,0.000000,0.000000,poisson,auto,50,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
29,0.001366,0.000081,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,25
30,0.161299,0.131201,0.016412,0.013414,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.800880,0.747890,0.815868,0.821818,0.734455,0.784182,0.036025,17
31,0.322392,0.047221,0.029463,0.014480,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.798637,0.766449,0.837723,0.833128,0.755325,0.798253,0.033552,11
32,0.704610,0.036507,0.051626,0.009811,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.792802,0.769069,0.840143,0.837775,0.758946,0.799747,0.033859,7
33,0.101202,0.015627,0.008618,0.006169,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.766908,0.766335,0.839505,0.810900,0.737259,0.784181,0.036313,18
34,0.349575,0.030347,0.027193,0.016904,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.809782,0.765698,0.837690,0.839523,0.754707,0.801480,0.035484,4
35,0.668983,0.037478,0.036979,0.015767,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.805765,0.770243,0.836853,0.834576,0.758654,0.801218,0.032170,5